// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authpb/authpb.proto

package authpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckServerStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckServerStatusRequest) Reset()         { *m = CheckServerStatusRequest{} }
func (m *CheckServerStatusRequest) String() string { return proto.CompactTextString(m) }
func (*CheckServerStatusRequest) ProtoMessage()    {}
func (*CheckServerStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{0}
}

func (m *CheckServerStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckServerStatusRequest.Unmarshal(m, b)
}
func (m *CheckServerStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckServerStatusRequest.Marshal(b, m, deterministic)
}
func (m *CheckServerStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckServerStatusRequest.Merge(m, src)
}
func (m *CheckServerStatusRequest) XXX_Size() int {
	return xxx_messageInfo_CheckServerStatusRequest.Size(m)
}
func (m *CheckServerStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckServerStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckServerStatusRequest proto.InternalMessageInfo

type CheckServerStatusResponse struct {
	ServerName           string   `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckServerStatusResponse) Reset()         { *m = CheckServerStatusResponse{} }
func (m *CheckServerStatusResponse) String() string { return proto.CompactTextString(m) }
func (*CheckServerStatusResponse) ProtoMessage()    {}
func (*CheckServerStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{1}
}

func (m *CheckServerStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckServerStatusResponse.Unmarshal(m, b)
}
func (m *CheckServerStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckServerStatusResponse.Marshal(b, m, deterministic)
}
func (m *CheckServerStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckServerStatusResponse.Merge(m, src)
}
func (m *CheckServerStatusResponse) XXX_Size() int {
	return xxx_messageInfo_CheckServerStatusResponse.Size(m)
}
func (m *CheckServerStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckServerStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckServerStatusResponse proto.InternalMessageInfo

func (m *CheckServerStatusResponse) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *CheckServerStatusResponse) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *CheckServerStatusResponse) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *CheckServerStatusResponse) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *CheckServerStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RegisterAccountRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,6,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	CompanyTerms         bool     `protobuf:"varint,7,opt,name=company_terms,json=companyTerms,proto3" json:"company_terms,omitempty"`
	GovtTerms            bool     `protobuf:"varint,8,opt,name=govt_terms,json=govtTerms,proto3" json:"govt_terms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAccountRequest) Reset()         { *m = RegisterAccountRequest{} }
func (m *RegisterAccountRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterAccountRequest) ProtoMessage()    {}
func (*RegisterAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{2}
}

func (m *RegisterAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAccountRequest.Unmarshal(m, b)
}
func (m *RegisterAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAccountRequest.Marshal(b, m, deterministic)
}
func (m *RegisterAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAccountRequest.Merge(m, src)
}
func (m *RegisterAccountRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterAccountRequest.Size(m)
}
func (m *RegisterAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAccountRequest proto.InternalMessageInfo

func (m *RegisterAccountRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterAccountRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterAccountRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

func (m *RegisterAccountRequest) GetCompanyTerms() bool {
	if m != nil {
		return m.CompanyTerms
	}
	return false
}

func (m *RegisterAccountRequest) GetGovtTerms() bool {
	if m != nil {
		return m.GovtTerms
	}
	return false
}

type RegisterAccountResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAccountResponse) Reset()         { *m = RegisterAccountResponse{} }
func (m *RegisterAccountResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterAccountResponse) ProtoMessage()    {}
func (*RegisterAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{3}
}

func (m *RegisterAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAccountResponse.Unmarshal(m, b)
}
func (m *RegisterAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAccountResponse.Marshal(b, m, deterministic)
}
func (m *RegisterAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAccountResponse.Merge(m, src)
}
func (m *RegisterAccountResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterAccountResponse.Size(m)
}
func (m *RegisterAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAccountResponse proto.InternalMessageInfo

func (m *RegisterAccountResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *RegisterAccountResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckServerStatusRequest)(nil), "authpb.CheckServerStatusRequest")
	proto.RegisterType((*CheckServerStatusResponse)(nil), "authpb.CheckServerStatusResponse")
	proto.RegisterType((*RegisterAccountRequest)(nil), "authpb.RegisterAccountRequest")
	proto.RegisterType((*RegisterAccountResponse)(nil), "authpb.RegisterAccountResponse")
}

func init() { proto.RegisterFile("authpb/authpb.proto", fileDescriptor_3057ffcbf9655ca4) }

var fileDescriptor_3057ffcbf9655ca4 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x53, 0x84, 0xda, 0x0e, 0x1a, 0x74, 0x35, 0x58, 0x6b, 0x14, 0xac, 0x17, 0xbc, 0x60,
	0xa2, 0x4f, 0x40, 0x3c, 0x79, 0x31, 0xa6, 0x78, 0xf0, 0x46, 0x96, 0x3a, 0xd0, 0x46, 0xda, 0xad,
	0xbb, 0x5b, 0x8c, 0x6f, 0xa1, 0xcf, 0xe3, 0xcb, 0x99, 0xfd, 0x03, 0x21, 0x02, 0x9e, 0xba, 0xf3,
	0xfb, 0xbe, 0x6d, 0xbf, 0xce, 0x0c, 0x1c, 0xd1, 0x4a, 0xa6, 0xe5, 0xf8, 0xc6, 0x3c, 0xfa, 0x25,
	0x67, 0x92, 0x11, 0xd7, 0x54, 0x51, 0x08, 0xc1, 0x7d, 0x8a, 0xc9, 0xdb, 0x10, 0xf9, 0x1c, 0xf9,
	0x50, 0x52, 0x59, 0x89, 0x18, 0xdf, 0x2b, 0x14, 0x32, 0xfa, 0x72, 0xe0, 0x74, 0x83, 0x28, 0x4a,
	0x56, 0x08, 0x24, 0x1d, 0x68, 0x0a, 0xcd, 0x47, 0x05, 0xcd, 0x31, 0x70, 0xba, 0x4e, 0xcf, 0x8f,
	0xc1, 0xa0, 0x47, 0x9a, 0x23, 0x21, 0x50, 0x4f, 0x99, 0x90, 0x41, 0x4d, 0x2b, 0xfa, 0xac, 0x58,
	0xc9, 0xb8, 0x0c, 0x76, 0x0c, 0x53, 0x67, 0xc5, 0x64, 0x96, 0x63, 0x50, 0x37, 0x4c, 0x9d, 0x49,
	0x1b, 0x5c, 0xa1, 0x3f, 0x17, 0x34, 0x34, 0xb5, 0x55, 0xf4, 0x5d, 0x83, 0x76, 0x8c, 0xd3, 0x4c,
	0x48, 0xe4, 0x83, 0x24, 0x61, 0x55, 0x21, 0x6d, 0x5a, 0x72, 0x0e, 0x30, 0xc9, 0xb8, 0x90, 0xab,
	0x71, 0x7c, 0x4d, 0x74, 0x9a, 0x33, 0xf0, 0x67, 0x74, 0xa1, 0x9a, 0x48, 0x9e, 0x02, 0x5a, 0x0c,
	0xc1, 0xab, 0x04, 0x72, 0xad, 0x99, 0x68, 0xcb, 0x9a, 0x1c, 0x43, 0x03, 0x73, 0x9a, 0xcd, 0x6c,
	0x3e, 0x53, 0xa8, 0x1b, 0x25, 0x15, 0xe2, 0x83, 0xf1, 0x57, 0x1b, 0x71, 0x59, 0x93, 0x6b, 0x38,
	0x48, 0x58, 0x31, 0xc9, 0x78, 0x3e, 0x5a, 0x7a, 0x5c, 0xed, 0x69, 0x59, 0xfe, 0xb4, 0xb0, 0x5e,
	0xc1, 0x7e, 0xc2, 0xf2, 0x92, 0x16, 0x9f, 0x23, 0x89, 0x3c, 0x17, 0xc1, 0x6e, 0xd7, 0xe9, 0x79,
	0xf1, 0x9e, 0x85, 0xcf, 0x8a, 0xa9, 0x3f, 0x9b, 0xb2, 0xb9, 0xb4, 0x0e, 0x4f, 0x3b, 0x7c, 0x45,
	0xb4, 0x1c, 0x3d, 0xc0, 0xc9, 0x5a, 0x4b, 0xec, 0x8c, 0xda, 0xe0, 0x72, 0x14, 0xd5, 0x4c, 0xda,
	0x7e, 0xd8, 0x6a, 0xa5, 0xbd, 0xb5, 0xd5, 0xf6, 0xde, 0xfe, 0x38, 0xd0, 0x1c, 0x54, 0x32, 0x55,
	0x03, 0xcf, 0x12, 0x24, 0x2f, 0x70, 0xb8, 0xb6, 0x00, 0xa4, 0xdb, 0xb7, 0x9b, 0xb4, 0x6d, 0x71,
	0xc2, 0xcb, 0x7f, 0x1c, 0x36, 0x59, 0x0c, 0xad, 0x3f, 0xa1, 0xc9, 0xc5, 0xe2, 0xd6, 0xe6, 0x01,
	0x87, 0x9d, 0xad, 0xba, 0x79, 0xe7, 0xd8, 0xd5, 0xab, 0x7d, 0xf7, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0xc7, 0xac, 0x89, 0x7a, 0xf1, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	CheckServerStatus(ctx context.Context, in *CheckServerStatusRequest, opts ...grpc.CallOption) (*CheckServerStatusResponse, error)
	RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) CheckServerStatus(ctx context.Context, in *CheckServerStatusRequest, opts ...grpc.CallOption) (*CheckServerStatusResponse, error) {
	out := new(CheckServerStatusResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/CheckServerStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error) {
	out := new(RegisterAccountResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/RegisterAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	CheckServerStatus(context.Context, *CheckServerStatusRequest) (*CheckServerStatusResponse, error)
	RegisterAccount(context.Context, *RegisterAccountRequest) (*RegisterAccountResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) CheckServerStatus(ctx context.Context, req *CheckServerStatusRequest) (*CheckServerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckServerStatus not implemented")
}
func (*UnimplementedAuthServiceServer) RegisterAccount(ctx context.Context, req *RegisterAccountRequest) (*RegisterAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAccount not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_CheckServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/CheckServerStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckServerStatus(ctx, req.(*CheckServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RegisterAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/RegisterAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterAccount(ctx, req.(*RegisterAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authpb.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckServerStatus",
			Handler:    _AuthService_CheckServerStatus_Handler,
		},
		{
			MethodName: "RegisterAccount",
			Handler:    _AuthService_RegisterAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authpb/authpb.proto",
}
